steps:
  # Build the Docker image--Image of docker file
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/cloud-run-tutorial-424007/new-web-repo-doc/web:latest'
      - '.'
 
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/cloud-run-tutorial-424007/new-web-repo-doc/web:latest'
 
  # Deploy to Cloud Run--name-> CLI goodle cloud sdk kit 
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args:
  #     - run
  #     - deploy
  #     - assessment
  #     - '--image'
  #     - 'us-central1-docker.pkg.dev/cloud-run-tutorial-424007/new-web-repo-doc/web:latest'
  #     - '--region'
  #     - us-central1
options:
  logging: CLOUD_LOGGING_ONLY
